# Generated by Django 4.0.5 on 2022-07-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products_category', '0002_alter_productscategory_options_and_more'),
        ('eshop_products', '0002_alter_product_options_alter_product_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, to='eshop_products_category.productscategory', verbose_name='دسته بندی های '),
        ),
    ]
