# Generated by Django 4.0.5 on 2022-07-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products_category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productscategory',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها '},
        ),
        migrations.AlterField(
            model_name='productscategory',
            name='name',
            field=models.CharField(max_length=150, verbose_name='عنوان در url'),
        ),
    ]
